version: '3.7'

networks:
  net:

services:
  api:
    image: profl/tsapi-boilerplate
    labels:
      - traefik.frontend.rule=api.docker.local
      - traefik.port=3000
    environment:
      - NODE_ENV=production
      - TYPEORM_LOGGING=false
      - TYPEORM_SYNCHRONIZE=false
    networks:
      - net

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=tsapi_boilerplate
    networks:
      - net
